language: node_js

node_js:
 - "6"

dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

env:
  global:
    - NODE_ENV=test
  matrix:
    - DB=memory
    - DB=mysql

notifications:
  email:
    - rfkelly@mozilla.com
    - jrgm@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - npm config set spin false

script:
  - if [ $DB == "mysql" ]; then ./scripts/start-travis-auth-db-mysql.sh; fi
  - COVERALLS_REPO_TOKEN=vKN3jjhAOwxkv9HG0VBX4EYIlWLPwiJ9d npm run test-ci
  - npm run test-e2e
  # Test fxa-auth-mailer
  - grunt templates
  - grunt l10n-extract
  # NSP check
  - grunt nsp
