language: node_js

# workaround for obsolete `temp` module 0.6
env:
  global:
    - TMPDIR=/tmp

node_js:
 - "0.10"
 - "0.12"
 - "4"

sudo: false

env:
  - NODE_ENV=test DB=memory
  - NODE_ENV=test DB=mysql

notifications:
  email:
    - zcarter@mozilla.com
    - dcoates@mozilla.com
    - jbonacci@mozilla.com
    - rfkelly@mozilla.com
    - jrgm@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - npm config set spin false

script:
  - if [ $DB == "mysql" ]; then echo '~*~ Starting auth-db-mysql'; (./scripts/start-local-test-mysql.sh &>/dev/null &); fi
  - npm test
  - grunt nsp --force
