language: node_js

node_js:
 - "6"

dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

env:
  global:
    - NODE_ENV=test
  matrix:
    - DB=memory

before_install:
  - npm config set spin false

script:
  - node test.js
