language: node_js

# workaround for obsolete `temp` module 0.6
env:
  global:
    - TMPDIR=/tmp

node_js:
 - "0.10"

services:
 - memcached

notifications:
  email:
    - zcarter@mozilla.com
    - dcoates@mozilla.com
    - jbonacci@mozilla.com
    - rfkelly@mozilla.com
    - achilton@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa"
    use_notice: false
    skip_join: false

before_install:
  - sudo apt-get install libgmp3-dev
  - npm config set spin false

script:
  - npm test
  - grunt validate-shrinkwrap --force
